check for release only on publish

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -89,20 +89,23 @@ jobs:
               ;;
           esac
 
-          case "$GITHUB_REF_NAME" in
-            master | master-* )
-              echo "head is master or master-*"
-              ;;
-            * )
-              echo "invalid release kind: $RELEASE_KIND_IN is not allowd for $GITHUB_REF_NAME"
-              exit 255
-              ;;
-          esac
+          if $PUBLISH; then
+            case "$GITHUB_REF_NAME" in
+              master | master-* )
+                echo "head is master or master-*"
+                ;;
+              * )
+                echo "invalid release kind: $RELEASE_KIND_IN is not allowd for $GITHUB_REF_NAME"
+                exit 255
+                ;;
+            esac
+          fi
 
           gh-export-variable VERSION "$(get-version)"
           gh-set-output version "$(get-version)"
         env:
           RELEASE_KIND_IN: ${{ github.event.inputs.release_kind }}
+          PUBLISH: ${{ inputs.publish }}
 
       # region changelog
       - name: Create Changelog
